name: hello world
on: 
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      
      - name: hello-world
        run: echo "Hello World!"
        #shell: bash

      - run: |
          java -version
          ls -la

  container-job:
    runs-on: ubuntu-latest
    container:
      image: amazoncorretto:8-alpine3.16
    steps:
      - name: check-java-version
        run: | 
          java -version
          ls -la

  depends-job:
    runs-on: ubuntu-latest
    needs: hello-world
    steps:
      - name: job-2
        run: echo "Depends"
