name: hello world
on: 
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      
      - name: hello-world
        run: echo "Hello World!"
        #shell: bash

      - run: ls -la